import { BusinessDataProvider, SearchParams, RawBusinessData } from '@/lib/providers/types';

function removeAccents(str: string): string {
  return str.normalize("NFD").replace(/[\u0300-\u036f]/g, "");
}

function haversineDistance(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth radius in km
  const dLat = (lat2 - lat1) * Math.PI / 180;
  const dLon = (lon2 - lon1) * Math.PI / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
    Math.sin(dLon / 2) * Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return R * c;
}

const mockData: RawBusinessData[] = [
  // 1. Barbearias (12)
  { id: 'mock-barbearia-1', name: 'Barbearia Imperial', category: 'Barbearia', lat: -16.6801, lon: -49.2530, phone: '(62) 99123-4567', website: 'https://barbeariaimperial.com.br', instagram: '@barbeariaimperial', facebook: 'https://facebook.com/barbeariaimperial', address: 'Rua 9, 120', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sab 09:00-20:00', rating: 4.8, reviewCount: 152, source: 'mock' },
  { id: 'mock-barbearia-2', name: 'Barbearia Estilo', category: 'Barbearia', lat: -16.6902, lon: -49.2631, phone: '(62) 99234-5678', website: 'http://barbeariaestilo.blogspot.com', instagram: '@barbeariaestilogo', facebook: undefined, address: 'Av. T-63, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sab 08:00-19:00', rating: 4.5, reviewCount: 89, source: 'mock' },
  { id: 'mock-barbearia-3', name: 'Barbearia do Chefe', category: 'Barbearia', lat: -16.6712, lon: -49.2410, phone: undefined, website: undefined, instagram: '@barbeariadochefe', facebook: 'https://facebook.com/barbeariadochefe', address: 'Av. Anhanguera, 5500', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.2, reviewCount: 45, source: 'mock' },
  { id: 'mock-barbearia-4', name: 'Barba & Navalha', category: 'Barbearia', lat: -16.7023, lon: -49.2711, phone: '(62) 98111-2233', website: 'https://barbaenavalha.com.br', instagram: undefined, facebook: undefined, address: 'Rua 15, 30', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Ter-Sab 09:00-21:00', rating: 4.9, reviewCount: 310, source: 'mock' },
  { id: 'mock-barbearia-5', name: 'Barbearia Classic Cut', category: 'Barbearia', lat: -16.7121, lon: -49.2801, phone: '(62) 98222-3344', website: undefined, instagram: '@classiccutgo', facebook: 'https://facebook.com/classiccut', address: 'Rua 137, 50', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Seg-Sab 10:00-20:00', rating: 4.7, reviewCount: 205, source: 'mock' },
  { id: 'mock-barbearia-6', name: 'Barbearia Vintage', category: 'Barbearia', lat: -16.6622, lon: -49.2312, phone: '(62) 99333-4455', website: 'http://www.barbeariavintage.wixsite.com/home', instagram: '@vintagebarbearia', facebook: undefined, address: 'Av. 24 de Outubro, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sab 08:00-18:00', rating: 4.4, reviewCount: 76, source: 'mock' },
  { id: 'mock-barbearia-7', name: 'Barbearia Dom Barba', category: 'Barbearia', lat: -16.7210, lon: -49.2905, phone: '(62) 99444-5566', website: undefined, instagram: undefined, facebook: 'https://facebook.com/dombarba', address: 'Av. Rio Verde, 330', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.6, reviewCount: 120, source: 'mock' },
  { id: 'mock-barbearia-8', name: 'Barbearia Arena', category: 'Barbearia', lat: -16.6501, lon: -49.2210, phone: '(62) 99555-6677', website: 'https://barbeariaarena.com.br', instagram: '@barbeariaarena', facebook: undefined, address: 'Rua 83, 20', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Sab 09:00-20:00', rating: 4.8, reviewCount: 250, source: 'mock' },
  { id: 'mock-barbearia-9', name: 'Barbearia Corte Real', category: 'Barbearia', lat: -16.3211, lon: -48.9510, phone: '(62) 99666-7788', website: undefined, instagram: '@cortereal', facebook: undefined, address: 'Av. Brasil, 440', city: 'Anápolis', state: 'GO', neighborhood: 'Centro', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.3, reviewCount: 65, source: 'mock' },
  { id: 'mock-barbearia-10', name: 'Barbearia Fio de Ouro', category: 'Barbearia', lat: -16.6912, lon: -49.2501, phone: '(62) 99777-8899', website: 'http://fiodeouro.blogspot.com', instagram: undefined, facebook: 'https://facebook.com/fiodeouro', address: 'Av. T-4, 550', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Ter-Sab 10:00-20:00', rating: 4.5, reviewCount: 95, source: 'mock' },
  { id: 'mock-barbearia-11', name: 'Barbearia O Bigode', category: 'Barbearia', lat: -16.6805, lon: -49.2605, phone: undefined, website: undefined, instagram: '@obigodebarbearia', facebook: undefined, address: 'Praça Universitária, 12', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Universitário', openingHours: 'Seg-Sex 09:00-19:00', rating: 4.1, reviewCount: 30, source: 'mock' },
  { id: 'mock-barbearia-12', name: 'Barbearia Lâmina', category: 'Barbearia', lat: -16.7301, lon: -49.2805, phone: '(62) 98888-9900', website: 'https://barbearialamina.com.br', instagram: '@barbearialamina', facebook: 'https://facebook.com/barbearialamina', address: 'Rua C-148, 45', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sab 09:00-21:00', rating: 4.9, reviewCount: 400, source: 'mock' },

  // 2. Restaurantes (12)
  { id: 'mock-restaurante-1', name: 'Sabor da Terra', category: 'Restaurante', lat: -16.6705, lon: -49.2450, phone: '(62) 3211-1000', website: 'https://sabordaterra.com.br', instagram: '@sabordaterrago', facebook: undefined, address: 'Av. E, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Seg-Dom 11:00-15:00', rating: 4.6, reviewCount: 230, source: 'mock' },
  { id: 'mock-restaurante-2', name: 'Cantinho Mineiro', category: 'Restaurante', lat: -16.6850, lon: -49.2550, phone: '(62) 3222-2000', website: undefined, instagram: '@cantinhomineiro', facebook: 'https://facebook.com/cantinhomineiro', address: 'Av. 85, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Sab 11:00-14:30', rating: 4.4, reviewCount: 150, source: 'mock' },
  { id: 'mock-restaurante-3', name: 'Restaurante Bom Prato', category: 'Restaurante', lat: -16.6750, lon: -49.2650, phone: '(62) 3233-3000', website: 'http://bompratogoiania.blogspot.com', instagram: undefined, facebook: undefined, address: 'Rua 3, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 11:00-14:00', rating: 3.9, reviewCount: 80, source: 'mock' },
  { id: 'mock-restaurante-4', name: 'Churrascaria Fogo de Chão', category: 'Restaurante', lat: -16.6950, lon: -49.2750, phone: '(62) 3244-4000', website: 'https://fogodechao.com.br', instagram: '@fogodechao', facebook: 'https://facebook.com/fogodechao', address: 'Av. T-10, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Dom 11:30-23:00', rating: 4.8, reviewCount: 500, source: 'mock' },
  { id: 'mock-restaurante-5', name: 'Restaurante Mar & Sol', category: 'Restaurante', lat: -16.7050, lon: -49.2850, phone: undefined, website: undefined, instagram: '@maresol', facebook: undefined, address: 'Rua 146, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Ter-Dom 11:00-16:00', rating: 4.2, reviewCount: 120, source: 'mock' },
  { id: 'mock-restaurante-6', name: 'Bistrô da Praça', category: 'Restaurante', lat: -16.6650, lon: -49.2350, phone: '(62) 3266-6000', website: 'https://bistrodapraca.com.br', instagram: '@bistrodapraca', facebook: undefined, address: 'Praça Tamandaré, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Oeste', openingHours: 'Ter-Sab 19:00-23:30', rating: 4.7, reviewCount: 350, source: 'mock' },
  { id: 'mock-restaurante-7', name: 'Restaurante Tempero Goiano', category: 'Restaurante', lat: -16.7150, lon: -49.2950, phone: '(62) 3277-7000', website: 'http://www.temperogoiano.wixsite.com/restaurante', instagram: undefined, facebook: 'https://facebook.com/temperogoiano', address: 'Av. T-9, 700', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sab 11:00-15:00', rating: 4.3, reviewCount: 90, source: 'mock' },
  { id: 'mock-restaurante-8', name: 'Cozinha da Vó', category: 'Restaurante', lat: -16.6550, lon: -49.2250, phone: '(62) 3288-8000', website: undefined, instagram: '@cozinhadavo', facebook: undefined, address: 'Rua 200, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Vila Nova', openingHours: 'Seg-Sex 11:00-14:00', rating: 4.5, reviewCount: 110, source: 'mock' },
  { id: 'mock-restaurante-9', name: 'Restaurante Sabor Caseiro', category: 'Restaurante', lat: -16.7250, lon: -49.2150, phone: undefined, website: undefined, instagram: undefined, facebook: undefined, address: 'Rua U-4, 900', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Pedro Ludovico', openingHours: 'Seg-Sex 11:00-14:00', rating: 4.0, reviewCount: 40, source: 'mock' },
  { id: 'mock-restaurante-10', name: 'Grill House', category: 'Restaurante', lat: -16.6450, lon: -49.2150, phone: '(62) 3300-0000', website: 'https://grillhouse.com.br', instagram: '@grillhouse', facebook: 'https://facebook.com/grillhouse', address: 'Av. Goiás, 1000', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Norte Ferroviário', openingHours: 'Seg-Dom 11:00-22:00', rating: 4.6, reviewCount: 280, source: 'mock' },
  { id: 'mock-restaurante-11', name: 'Restaurante Paladar', category: 'Restaurante', lat: -16.8250, lon: -49.2650, phone: '(62) 3311-1111', website: undefined, instagram: '@paladar', facebook: undefined, address: 'Av. Independência, 1100', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Centro', openingHours: 'Seg-Sab 11:00-15:00', rating: 4.1, reviewCount: 70, source: 'mock' },
  { id: 'mock-restaurante-12', name: 'Restaurante Primavera', category: 'Restaurante', lat: -16.3350, lon: -48.9650, phone: '(62) 3322-2222', website: 'http://primavera.blogspot.com', instagram: undefined, facebook: 'https://facebook.com/primavera', address: 'Praça Bom Jesus, 1200', city: 'Anápolis', state: 'GO', neighborhood: 'Centro', openingHours: 'Seg-Sex 11:00-14:00', rating: 3.8, reviewCount: 50, source: 'mock' },

  // 3. Clínicas Odontológicas (10)
  { id: 'mock-odonto-1', name: 'OdontoVida', category: 'Clínica Odontológica', lat: -16.6811, lon: -49.2511, phone: '(62) 99111-1111', website: 'https://odontovida.com.br', instagram: '@odontovida', facebook: undefined, address: 'Av. T-1, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.8, reviewCount: 150, source: 'mock' },
  { id: 'mock-odonto-2', name: 'Sorriso Perfeito', category: 'Clínica Odontológica', lat: -16.6911, lon: -49.2611, phone: '(62) 99222-2222', website: undefined, instagram: '@sorrisoperfeito', facebook: 'https://facebook.com/sorrisoperfeito', address: 'Rua 9, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Oeste', openingHours: 'Seg-Sab 08:00-12:00', rating: 4.9, reviewCount: 210, source: 'mock' },
  { id: 'mock-odonto-3', name: 'Clínica Dental Care', category: 'Clínica Odontológica', lat: -16.6711, lon: -49.2411, phone: '(62) 99333-3333', website: 'http://www.dentalcare.wixsite.com/clinica', instagram: undefined, facebook: undefined, address: 'Av. Tocantins, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 08:00-17:00', rating: 4.5, reviewCount: 90, source: 'mock' },
  { id: 'mock-odonto-4', name: 'OdontoMax', category: 'Clínica Odontológica', lat: -16.7011, lon: -49.2711, phone: undefined, website: 'https://odontomax.com.br', instagram: '@odontomax', facebook: undefined, address: 'Av. 136, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Seg-Sex 09:00-19:00', rating: 4.7, reviewCount: 180, source: 'mock' },
  { id: 'mock-odonto-5', name: 'Clínica Oral Premium', category: 'Clínica Odontológica', lat: -16.7111, lon: -49.2811, phone: '(62) 99555-5555', website: undefined, instagram: '@oralpremium', facebook: 'https://facebook.com/oralpremium', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sab 08:00-18:00', rating: 4.6, reviewCount: 130, source: 'mock' },
  { id: 'mock-odonto-6', name: 'Sorriso & Saúde', category: 'Clínica Odontológica', lat: -16.6611, lon: -49.2311, phone: '(62) 99666-6666', website: 'http://sorrisosaude.blogspot.com', instagram: undefined, facebook: undefined, address: 'Av. Castelo Branco, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.2, reviewCount: 70, source: 'mock' },
  { id: 'mock-odonto-7', name: 'OdontoCenter', category: 'Clínica Odontológica', lat: -16.7211, lon: -49.2911, phone: '(62) 99777-7777', website: 'https://odontocenter.com.br', instagram: '@odontocenter', facebook: 'https://facebook.com/odontocenter', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Sex 08:00-19:00', rating: 4.4, reviewCount: 110, source: 'mock' },
  { id: 'mock-odonto-8', name: 'Clínica Dentes Brancos', category: 'Clínica Odontológica', lat: -16.6511, lon: -49.2211, phone: undefined, website: undefined, instagram: undefined, facebook: undefined, address: 'Rua 10, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Universitário', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.0, reviewCount: 40, source: 'mock' },
  { id: 'mock-odonto-9', name: 'Odontologia Integrada', category: 'Clínica Odontológica', lat: -16.3211, lon: -48.9511, phone: '(62) 99999-9999', website: 'https://odontointegrada.com.br', instagram: '@odontointegrada', facebook: undefined, address: 'Av. Goiás, 900', city: 'Anápolis', state: 'GO', neighborhood: 'Centro', openingHours: 'Seg-Sab 08:00-12:00', rating: 4.8, reviewCount: 160, source: 'mock' },
  { id: 'mock-odonto-10', name: 'OdontoPlus', category: 'Clínica Odontológica', lat: -16.6911, lon: -49.2511, phone: '(62) 99000-0000', website: undefined, instagram: '@odontoplus', facebook: 'https://facebook.com/odontoplus', address: 'Av. 85, 1000', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 95, source: 'mock' },

  // 4. Academias (10)
  { id: 'mock-academia-1', name: 'Academia Força Total', category: 'Academia', lat: -16.6822, lon: -49.2522, phone: '(62) 98111-1111', website: 'https://forcatotal.com.br', instagram: '@forcatotal', facebook: undefined, address: 'Av. T-2, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 06:00-22:00', rating: 4.7, reviewCount: 300, source: 'mock' },
  { id: 'mock-academia-2', name: 'Iron Gym', category: 'Academia', lat: -16.6922, lon: -49.2622, phone: '(62) 98222-2222', website: undefined, instagram: '@irongymgo', facebook: 'https://facebook.com/irongym', address: 'Rua 15, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Seg-Sex 05:30-23:00', rating: 4.9, reviewCount: 450, source: 'mock' },
  { id: 'mock-academia-3', name: 'Academia Corpo & Mente', category: 'Academia', lat: -16.6722, lon: -49.2422, phone: '(62) 98333-3333', website: 'http://corpoemente.blogspot.com', instagram: undefined, facebook: undefined, address: 'Av. Paranaíba, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 06:00-21:00', rating: 4.3, reviewCount: 120, source: 'mock' },
  { id: 'mock-academia-4', name: 'Fitness Prime', category: 'Academia', lat: -16.7022, lon: -49.2722, phone: undefined, website: 'https://fitnessprime.com.br', instagram: '@fitnessprime', facebook: undefined, address: 'Av. Jamel Cecílio, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Seg-Dom 06:00-22:00', rating: 4.8, reviewCount: 380, source: 'mock' },
  { id: 'mock-academia-5', name: 'Academia Evolução', category: 'Academia', lat: -16.7122, lon: -49.2822, phone: '(62) 98555-5555', website: undefined, instagram: '@evolucao', facebook: 'https://facebook.com/evolucao', address: 'Av. T-9, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sex 06:00-22:00', rating: 4.5, reviewCount: 200, source: 'mock' },
  { id: 'mock-academia-6', name: 'Power Gym', category: 'Academia', lat: -16.6622, lon: -49.2322, phone: '(62) 98666-6666', website: 'http://www.powergym.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. Anhanguera, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sex 06:00-22:00', rating: 4.4, reviewCount: 150, source: 'mock' },
  { id: 'mock-academia-7', name: 'Academia Saúde em Dia', category: 'Academia', lat: -16.7222, lon: -49.2922, phone: '(62) 98777-7777', website: 'https://saudeemdia.com.br', instagram: '@saudeemdia', facebook: 'https://facebook.com/saudeemdia', address: 'Av. Independência, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Centro', openingHours: 'Seg-Sex 06:00-21:00', rating: 4.6, reviewCount: 220, source: 'mock' },
  { id: 'mock-academia-8', name: 'CrossFit Goiânia', category: 'Academia', lat: -16.6522, lon: -49.2222, phone: undefined, website: undefined, instagram: '@crossfitgoiania', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Sex 06:00-21:00', rating: 4.9, reviewCount: 400, source: 'mock' },
  { id: 'mock-academia-9', name: 'Academia Titanium', category: 'Academia', lat: -16.3222, lon: -48.9522, phone: '(62) 98999-9999', website: 'https://titanium.com.br', instagram: '@titanium', facebook: undefined, address: 'Av. Universitária, 900', city: 'Anápolis', state: 'GO', neighborhood: 'Jardim Bandeirante', openingHours: 'Seg-Sex 06:00-22:00', rating: 4.7, reviewCount: 280, source: 'mock' },
  { id: 'mock-academia-10', name: 'Flex Fitness', category: 'Academia', lat: -16.6922, lon: -49.2522, phone: '(62) 98000-0000', website: undefined, instagram: '@flexfitness', facebook: 'https://facebook.com/flexfitness', address: 'Av. Mutirão, 1000', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 06:00-23:00', rating: 4.8, reviewCount: 350, source: 'mock' },

  // 5. Salões de Beleza (10)
  { id: 'mock-salao-1', name: 'Beleza Pura', category: 'Salão de Beleza', lat: -16.6833, lon: -49.2533, phone: '(62) 97111-1111', website: 'https://belezapura.com.br', instagram: '@belezapura', facebook: undefined, address: 'Av. T-4, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.7, reviewCount: 180, source: 'mock' },
  { id: 'mock-salao-2', name: 'Studio Hair', category: 'Salão de Beleza', lat: -16.6933, lon: -49.2633, phone: '(62) 97222-2222', website: undefined, instagram: '@studiohairgo', facebook: 'https://facebook.com/studiohair', address: 'Rua 137, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Ter-Sab 09:00-20:00', rating: 4.9, reviewCount: 250, source: 'mock' },
  { id: 'mock-salao-3', name: 'Salão Glamour', category: 'Salão de Beleza', lat: -16.6733, lon: -49.2433, phone: '(62) 97333-3333', website: 'http://salaoglamour.blogspot.com', instagram: undefined, facebook: undefined, address: 'Rua 4, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Ter-Sab 09:00-18:00', rating: 4.4, reviewCount: 90, source: 'mock' },
  { id: 'mock-salao-4', name: 'Beleza & Estilo', category: 'Salão de Beleza', lat: -16.7033, lon: -49.2733, phone: undefined, website: 'https://belezaeestilo.com.br', instagram: '@belezaeestilo', facebook: undefined, address: 'Av. Deputado Jamel Cecílio, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Ter-Sab 10:00-20:00', rating: 4.8, reviewCount: 210, source: 'mock' },
  { id: 'mock-salao-5', name: 'Salão Dona Maria', category: 'Salão de Beleza', lat: -16.7133, lon: -49.2833, phone: '(62) 97555-5555', website: undefined, instagram: '@salaodonamaria', facebook: 'https://facebook.com/salaodonamaria', address: 'Av. C-104, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Ter-Sab 08:00-18:00', rating: 4.6, reviewCount: 150, source: 'mock' },
  { id: 'mock-salao-6', name: 'Hair Design', category: 'Salão de Beleza', lat: -16.6633, lon: -49.2333, phone: '(62) 97666-6666', website: 'http://www.hairdesign.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.3, reviewCount: 110, source: 'mock' },
  { id: 'mock-salao-7', name: 'Salão Encanto', category: 'Salão de Beleza', lat: -16.7233, lon: -49.2933, phone: '(62) 97777-7777', website: 'https://salaoencanto.com.br', instagram: '@salaoencanto', facebook: 'https://facebook.com/salaoencanto', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.5, reviewCount: 130, source: 'mock' },
  { id: 'mock-salao-8', name: 'Studio Beauty', category: 'Salão de Beleza', lat: -16.6533, lon: -49.2233, phone: undefined, website: undefined, instagram: '@studiobeauty', facebook: undefined, address: 'Rua 84, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.8, reviewCount: 190, source: 'mock' },
  { id: 'mock-salao-9', name: 'Salão Charme', category: 'Salão de Beleza', lat: -16.3233, lon: -48.9533, phone: '(62) 97999-9999', website: 'https://salaocharme.com.br', instagram: '@salaocharme', facebook: undefined, address: 'Av. Minas Gerais, 900', city: 'Anápolis', state: 'GO', neighborhood: 'Jundiaí', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.7, reviewCount: 160, source: 'mock' },
  { id: 'mock-salao-10', name: 'Beleza Natural', category: 'Salão de Beleza', lat: -16.6933, lon: -49.2533, phone: '(62) 97000-0000', website: undefined, instagram: '@belezanatural', facebook: 'https://facebook.com/belezanatural', address: 'Av. T-63, 1000', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Ter-Sab 09:00-19:00', rating: 4.6, reviewCount: 140, source: 'mock' },

  // 6. Oficinas Mecânicas (10)
  { id: 'mock-oficina-1', name: 'Auto Center Silva', category: 'Oficina Mecânica', lat: -16.6844, lon: -49.2544, phone: '(62) 96111-1111', website: 'https://autocentersilva.com.br', instagram: '@autocentersilva', facebook: undefined, address: 'Av. T-9, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 120, source: 'mock' },
  { id: 'mock-oficina-2', name: 'Oficina do Marcão', category: 'Oficina Mecânica', lat: -16.6944, lon: -49.2644, phone: '(62) 96222-2222', website: undefined, instagram: undefined, facebook: 'https://facebook.com/oficinadomarcao', address: 'Av. C-1, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.8, reviewCount: 200, source: 'mock' },
  { id: 'mock-oficina-3', name: 'Mecânica Rápida', category: 'Oficina Mecânica', lat: -16.6744, lon: -49.2444, phone: '(62) 96333-3333', website: 'http://mecanicarapida.blogspot.com', instagram: undefined, facebook: undefined, address: 'Av. Independência, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.1, reviewCount: 60, source: 'mock' },
  { id: 'mock-oficina-4', name: 'Auto Elétrica Central', category: 'Oficina Mecânica', lat: -16.7044, lon: -49.2744, phone: undefined, website: 'https://autoeletricacentral.com.br', instagram: '@autoeletricacentral', facebook: undefined, address: 'Av. 85, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.6, reviewCount: 150, source: 'mock' },
  { id: 'mock-oficina-5', name: 'Oficina Car Fix', category: 'Oficina Mecânica', lat: -16.7144, lon: -49.2844, phone: '(62) 96555-5555', website: undefined, instagram: '@carfix', facebook: 'https://facebook.com/carfix', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.4, reviewCount: 110, source: 'mock' },
  { id: 'mock-oficina-6', name: 'Mecânica Premium', category: 'Oficina Mecânica', lat: -16.6644, lon: -49.2344, phone: '(62) 96666-6666', website: 'http://www.mecanicapremium.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. Castelo Branco, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.7, reviewCount: 180, source: 'mock' },
  { id: 'mock-oficina-7', name: 'Auto Service Express', category: 'Oficina Mecânica', lat: -16.7244, lon: -49.2944, phone: '(62) 96777-7777', website: 'https://autoserviceexpress.com.br', instagram: '@autoserviceexpress', facebook: 'https://facebook.com/autoserviceexpress', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 130, source: 'mock' },
  { id: 'mock-oficina-8', name: 'Oficina Motortech', category: 'Oficina Mecânica', lat: -16.6544, lon: -49.2244, phone: undefined, website: undefined, instagram: '@motortech', facebook: undefined, address: 'Av. Universitária, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Universitário', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.6, reviewCount: 140, source: 'mock' },
  { id: 'mock-oficina-9', name: 'Mecânica Confiança', category: 'Oficina Mecânica', lat: -16.3244, lon: -48.9544, phone: '(62) 96999-9999', website: 'https://mecanicaconfianca.com.br', instagram: '@mecanicaconfianca', facebook: undefined, address: 'Av. Brasil, 900', city: 'Anápolis', state: 'GO', neighborhood: 'Centro', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.8, reviewCount: 190, source: 'mock' },
  { id: 'mock-oficina-10', name: 'Auto Repair Center', category: 'Oficina Mecânica', lat: -16.6944, lon: -49.2544, phone: '(62) 96000-0000', website: undefined, instagram: '@autorepair', facebook: 'https://facebook.com/autorepair', address: 'Av. Mutirão, 1000', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.7, reviewCount: 160, source: 'mock' },

  // 7. Pizzarias (8)
  { id: 'mock-pizzaria-1', name: 'Pizza Express', category: 'Pizzaria', lat: -16.6855, lon: -49.2555, phone: '(62) 95111-1111', website: 'https://pizzaexpress.com.br', instagram: '@pizzaexpress', facebook: undefined, address: 'Av. T-4, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Dom 18:00-23:30', rating: 4.6, reviewCount: 250, source: 'mock' },
  { id: 'mock-pizzaria-2', name: 'Pizzaria Bella Napoli', category: 'Pizzaria', lat: -16.6955, lon: -49.2655, phone: '(62) 95222-2222', website: undefined, instagram: '@bellanapoli', facebook: 'https://facebook.com/bellanapoli', address: 'Rua 15, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Ter-Dom 18:30-23:30', rating: 4.9, reviewCount: 400, source: 'mock' },
  { id: 'mock-pizzaria-3', name: 'Forno & Massa', category: 'Pizzaria', lat: -16.6755, lon: -49.2455, phone: '(62) 95333-3333', website: 'http://fornoemassa.blogspot.com', instagram: undefined, facebook: undefined, address: 'Rua 3, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Dom 18:00-23:00', rating: 4.3, reviewCount: 150, source: 'mock' },
  { id: 'mock-pizzaria-4', name: 'Pizzaria Don Giovanni', category: 'Pizzaria', lat: -16.7055, lon: -49.2755, phone: undefined, website: 'https://dongiovanni.com.br', instagram: '@dongiovanni', facebook: undefined, address: 'Av. Jamel Cecílio, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Ter-Dom 18:00-00:00', rating: 4.8, reviewCount: 320, source: 'mock' },
  { id: 'mock-pizzaria-5', name: 'Pizza da Hora', category: 'Pizzaria', lat: -16.7155, lon: -49.2855, phone: '(62) 95555-5555', website: undefined, instagram: '@pizzadahora', facebook: 'https://facebook.com/pizzadahora', address: 'Av. T-9, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Dom 18:00-23:30', rating: 4.5, reviewCount: 200, source: 'mock' },
  { id: 'mock-pizzaria-6', name: 'Pizzaria Italiana', category: 'Pizzaria', lat: -16.6655, lon: -49.2355, phone: '(62) 95666-6666', website: 'http://www.pizzariaitaliana.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Ter-Dom 18:00-23:00', rating: 4.4, reviewCount: 180, source: 'mock' },
  { id: 'mock-pizzaria-7', name: 'Mega Pizza', category: 'Pizzaria', lat: -16.7255, lon: -49.2955, phone: '(62) 95777-7777', website: 'https://megapizza.com.br', instagram: '@megapizza', facebook: 'https://facebook.com/megapizza', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Dom 18:00-23:30', rating: 4.6, reviewCount: 220, source: 'mock' },
  { id: 'mock-pizzaria-8', name: 'Pizzaria Forno a Lenha', category: 'Pizzaria', lat: -16.6555, lon: -49.2255, phone: undefined, website: undefined, instagram: '@fornoalenha', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Ter-Dom 18:00-23:30', rating: 4.7, reviewCount: 270, source: 'mock' },

  // 8. Clínicas Veterinárias (8)
  { id: 'mock-vet-1', name: 'Pet Vida', category: 'Clínica Veterinária', lat: -16.6866, lon: -49.2566, phone: '(62) 94111-1111', website: 'https://petvida.com.br', instagram: '@petvida', facebook: undefined, address: 'Av. T-2, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sab 08:00-18:00', rating: 4.8, reviewCount: 200, source: 'mock' },
  { id: 'mock-vet-2', name: 'Clínica Vet Amigo', category: 'Clínica Veterinária', lat: -16.6966, lon: -49.2666, phone: '(62) 94222-2222', website: undefined, instagram: '@vetamigo', facebook: 'https://facebook.com/vetamigo', address: 'Rua 15, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: '24h', rating: 4.9, reviewCount: 350, source: 'mock' },
  { id: 'mock-vet-3', name: 'Veterinária Bicho Feliz', category: 'Clínica Veterinária', lat: -16.6766, lon: -49.2466, phone: '(62) 94333-3333', website: 'http://bichofeliz.blogspot.com', instagram: undefined, facebook: undefined, address: 'Rua 4, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.3, reviewCount: 120, source: 'mock' },
  { id: 'mock-vet-4', name: 'Clínica Animal Care', category: 'Clínica Veterinária', lat: -16.7066, lon: -49.2766, phone: undefined, website: 'https://animalcare.com.br', instagram: '@animalcare', facebook: undefined, address: 'Av. E, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Seg-Sab 08:00-18:00', rating: 4.7, reviewCount: 280, source: 'mock' },
  { id: 'mock-vet-5', name: 'Vet Center', category: 'Clínica Veterinária', lat: -16.7166, lon: -49.2866, phone: '(62) 94555-5555', website: undefined, instagram: '@vetcenter', facebook: 'https://facebook.com/vetcenter', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: '24h', rating: 4.6, reviewCount: 220, source: 'mock' },
  { id: 'mock-vet-6', name: 'Clínica PetLove', category: 'Clínica Veterinária', lat: -16.6666, lon: -49.2366, phone: '(62) 94666-6666', website: 'http://www.petlove.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 160, source: 'mock' },
  { id: 'mock-vet-7', name: 'Veterinária Saúde Animal', category: 'Clínica Veterinária', lat: -16.7266, lon: -49.2966, phone: '(62) 94777-7777', website: 'https://saudeanimal.com.br', instagram: '@saudeanimal', facebook: 'https://facebook.com/saudeanimal', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Sab 08:00-18:00', rating: 4.6, reviewCount: 190, source: 'mock' },
  { id: 'mock-vet-8', name: 'Vet Premium', category: 'Clínica Veterinária', lat: -16.6566, lon: -49.2266, phone: undefined, website: undefined, instagram: '@vetpremium', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: '24h', rating: 4.9, reviewCount: 310, source: 'mock' },

  // 9. Imobiliárias (8)
  { id: 'mock-imob-1', name: 'Imobiliária Lar Doce', category: 'Imobiliária', lat: -16.6877, lon: -49.2577, phone: '(62) 93111-1111', website: 'https://lardoce.com.br', instagram: '@lardoceimoveis', facebook: undefined, address: 'Av. T-4, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 90, source: 'mock' },
  { id: 'mock-imob-2', name: 'Premium Imóveis', category: 'Imobiliária', lat: -16.6977, lon: -49.2677, phone: '(62) 93222-2222', website: undefined, instagram: '@premiumimoveis', facebook: 'https://facebook.com/premiumimoveis', address: 'Rua 137, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.8, reviewCount: 150, source: 'mock' },
  { id: 'mock-imob-3', name: 'Casa & Cia', category: 'Imobiliária', lat: -16.6777, lon: -49.2477, phone: '(62) 93333-3333', website: 'http://casaecia.blogspot.com', instagram: undefined, facebook: undefined, address: 'Av. Goiás, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.1, reviewCount: 50, source: 'mock' },
  { id: 'mock-imob-4', name: 'Imobiliária Horizonte', category: 'Imobiliária', lat: -16.7077, lon: -49.2777, phone: undefined, website: 'https://imobiliariahorizonte.com.br', instagram: '@imobiliariahorizonte', facebook: undefined, address: 'Av. Jamel Cecílio, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.6, reviewCount: 110, source: 'mock' },
  { id: 'mock-imob-5', name: 'Imobiliária Cidade', category: 'Imobiliária', lat: -16.7177, lon: -49.2877, phone: '(62) 93555-5555', website: undefined, instagram: '@imobcidade', facebook: 'https://facebook.com/imobcidade', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.4, reviewCount: 80, source: 'mock' },
  { id: 'mock-imob-6', name: 'Top Imóveis', category: 'Imobiliária', lat: -16.6677, lon: -49.2377, phone: '(62) 93666-6666', website: 'http://www.topimoveis.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.3, reviewCount: 70, source: 'mock' },
  { id: 'mock-imob-7', name: 'Imobiliária Confiança', category: 'Imobiliária', lat: -16.7277, lon: -49.2977, phone: '(62) 93777-7777', website: 'https://imobconfianca.com.br', instagram: '@imobconfianca', facebook: 'https://facebook.com/imobconfianca', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 95, source: 'mock' },
  { id: 'mock-imob-8', name: 'Real Imóveis', category: 'Imobiliária', lat: -16.6577, lon: -49.2277, phone: undefined, website: undefined, instagram: '@realimoveis', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.7, reviewCount: 130, source: 'mock' },

  // 10. Escritórios de Advocacia (8)
  { id: 'mock-adv-1', name: 'Advocacia Silva & Associados', category: 'Escritório de Advocacia', lat: -16.6888, lon: -49.2588, phone: '(62) 92111-1111', website: 'https://silvaadvogados.com.br', instagram: '@silvaadvogados', facebook: undefined, address: 'Av. T-2, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.8, reviewCount: 60, source: 'mock' },
  { id: 'mock-adv-2', name: 'Escritório Jurídico Souza', category: 'Escritório de Advocacia', lat: -16.6988, lon: -49.2688, phone: '(62) 92222-2222', website: undefined, instagram: undefined, facebook: 'https://facebook.com/juridicosouza', address: 'Rua 15, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.9, reviewCount: 80, source: 'mock' },
  { id: 'mock-adv-3', name: 'Advogados Associados', category: 'Escritório de Advocacia', lat: -16.6788, lon: -49.2488, phone: '(62) 92333-3333', website: 'http://advogadosassoc.blogspot.com', instagram: undefined, facebook: undefined, address: 'Av. Goiás, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.2, reviewCount: 40, source: 'mock' },
  { id: 'mock-adv-4', name: 'Direito & Justiça', category: 'Escritório de Advocacia', lat: -16.7088, lon: -49.2788, phone: undefined, website: 'https://direitoejustica.com.br', instagram: '@direitoejustica', facebook: undefined, address: 'Av. Jamel Cecílio, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.7, reviewCount: 70, source: 'mock' },
  { id: 'mock-adv-5', name: 'Advocacia Moderna', category: 'Escritório de Advocacia', lat: -16.7188, lon: -49.2888, phone: '(62) 92555-5555', website: undefined, instagram: '@advmoderna', facebook: 'https://facebook.com/advmoderna', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.5, reviewCount: 50, source: 'mock' },
  { id: 'mock-adv-6', name: 'Escritório Legal', category: 'Escritório de Advocacia', lat: -16.6688, lon: -49.2388, phone: '(62) 92666-6666', website: 'http://www.escritoriolegal.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.4, reviewCount: 45, source: 'mock' },
  { id: 'mock-adv-7', name: 'Advocacia Defesa Total', category: 'Escritório de Advocacia', lat: -16.7288, lon: -49.2988, phone: '(62) 92777-7777', website: 'https://defesatotal.com.br', instagram: '@defesatotal', facebook: 'https://facebook.com/defesatotal', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.6, reviewCount: 55, source: 'mock' },
  { id: 'mock-adv-8', name: 'Jurídico Center', category: 'Escritório de Advocacia', lat: -16.6588, lon: -49.2288, phone: undefined, website: undefined, instagram: '@juridicocenter', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Sex 08:00-18:00', rating: 4.8, reviewCount: 75, source: 'mock' },

  // 11. Padarias (8)
  { id: 'mock-padaria-1', name: 'Padaria Pão Quente', category: 'Padaria', lat: -16.6899, lon: -49.2599, phone: '(62) 91111-1111', website: 'https://paoquente.com.br', instagram: '@paoquente', facebook: undefined, address: 'Av. T-4, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: 'Seg-Dom 06:00-20:00', rating: 4.6, reviewCount: 150, source: 'mock' },
  { id: 'mock-padaria-2', name: 'Padaria Trigo Dourado', category: 'Padaria', lat: -16.6999, lon: -49.2699, phone: '(62) 91222-2222', website: undefined, instagram: '@trigodourado', facebook: 'https://facebook.com/trigodourado', address: 'Rua 15, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: 'Seg-Dom 06:00-21:00', rating: 4.8, reviewCount: 220, source: 'mock' },
  { id: 'mock-padaria-3', name: 'Padaria Aroma', category: 'Padaria', lat: -16.6799, lon: -49.2499, phone: '(62) 91333-3333', website: 'http://padariaaroma.blogspot.com', instagram: undefined, facebook: undefined, address: 'Rua 3, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: 'Seg-Sab 06:00-19:00', rating: 4.2, reviewCount: 90, source: 'mock' },
  { id: 'mock-padaria-4', name: 'Padaria São José', category: 'Padaria', lat: -16.7099, lon: -49.2799, phone: undefined, website: 'https://padariasaojose.com.br', instagram: '@padariasaojose', facebook: undefined, address: 'Av. E, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: 'Seg-Dom 06:00-20:00', rating: 4.7, reviewCount: 180, source: 'mock' },
  { id: 'mock-padaria-5', name: 'Panificadora Central', category: 'Padaria', lat: -16.7199, lon: -49.2899, phone: '(62) 91555-5555', website: undefined, instagram: '@panificadoracentral', facebook: 'https://facebook.com/panificadoracentral', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: 'Seg-Dom 06:00-21:00', rating: 4.5, reviewCount: 140, source: 'mock' },
  { id: 'mock-padaria-6', name: 'Padaria Delícia', category: 'Padaria', lat: -16.6699, lon: -49.2399, phone: '(62) 91666-6666', website: 'http://www.padariadelicia.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: 'Seg-Sab 06:00-20:00', rating: 4.4, reviewCount: 110, source: 'mock' },
  { id: 'mock-padaria-7', name: 'Padaria & Confeitaria Sabor', category: 'Padaria', lat: -16.7299, lon: -49.2999, phone: '(62) 91777-7777', website: 'https://confeitariasabor.com.br', instagram: '@confeitariasabor', facebook: 'https://facebook.com/confeitariasabor', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: 'Seg-Dom 06:00-20:00', rating: 4.6, reviewCount: 160, source: 'mock' },
  { id: 'mock-padaria-8', name: 'Padaria Tradição', category: 'Padaria', lat: -16.6599, lon: -49.2299, phone: undefined, website: undefined, instagram: '@padariatradicao', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: 'Seg-Dom 06:00-21:00', rating: 4.8, reviewCount: 200, source: 'mock' },

  // 12. Hotéis/Pousadas (8)
  { id: 'mock-hotel-1', name: 'Hotel Cerrado', category: 'Hotel/Pousada', lat: -16.6800, lon: -49.2500, phone: '(62) 90111-1111', website: 'https://hotelcerrado.com.br', instagram: '@hotelcerrado', facebook: undefined, address: 'Av. T-4, 100', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Bueno', openingHours: '24h', rating: 4.5, reviewCount: 300, source: 'mock' },
  { id: 'mock-hotel-2', name: 'Pousada Sol Nascente', category: 'Hotel/Pousada', lat: -16.6900, lon: -49.2600, phone: '(62) 90222-2222', website: undefined, instagram: '@pousadasolnascente', facebook: 'https://facebook.com/pousadasolnascente', address: 'Rua 15, 200', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Marista', openingHours: '24h', rating: 4.8, reviewCount: 450, source: 'mock' },
  { id: 'mock-hotel-3', name: 'Hotel Executive', category: 'Hotel/Pousada', lat: -16.6700, lon: -49.2400, phone: '(62) 90333-3333', website: 'http://hotelexecutive.blogspot.com', instagram: undefined, facebook: undefined, address: 'Av. Goiás, 300', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Central', openingHours: '24h', rating: 4.2, reviewCount: 180, source: 'mock' },
  { id: 'mock-hotel-4', name: 'Pousada Verde', category: 'Hotel/Pousada', lat: -16.7000, lon: -49.2700, phone: undefined, website: 'https://pousadaverde.com.br', instagram: '@pousadaverde', facebook: undefined, address: 'Av. Jamel Cecílio, 400', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim Goiás', openingHours: '24h', rating: 4.7, reviewCount: 280, source: 'mock' },
  { id: 'mock-hotel-5', name: 'Hotel Plaza', category: 'Hotel/Pousada', lat: -16.7100, lon: -49.2800, phone: '(62) 90555-5555', website: undefined, instagram: '@hotelplaza', facebook: 'https://facebook.com/hotelplaza', address: 'Av. T-63, 500', city: 'Goiânia', state: 'GO', neighborhood: 'Jardim América', openingHours: '24h', rating: 4.4, reviewCount: 210, source: 'mock' },
  { id: 'mock-hotel-6', name: 'Hotel Comfort Inn', category: 'Hotel/Pousada', lat: -16.6600, lon: -49.2300, phone: '(62) 90666-6666', website: 'http://www.hotelcomfortinn.wixsite.com/home', instagram: undefined, facebook: undefined, address: 'Av. 24 de Outubro, 600', city: 'Goiânia', state: 'GO', neighborhood: 'Campinas', openingHours: '24h', rating: 4.3, reviewCount: 150, source: 'mock' },
  { id: 'mock-hotel-7', name: 'Pousada das Flores', category: 'Hotel/Pousada', lat: -16.7200, lon: -49.2900, phone: '(62) 90777-7777', website: 'https://pousadadasflores.com.br', instagram: '@pousadadasflores', facebook: 'https://facebook.com/pousadadasflores', address: 'Av. Rio Verde, 700', city: 'Aparecida de Goiânia', state: 'GO', neighborhood: 'Vila Brasília', openingHours: '24h', rating: 4.6, reviewCount: 190, source: 'mock' },
  { id: 'mock-hotel-8', name: 'Hotel Business', category: 'Hotel/Pousada', lat: -16.6500, lon: -49.2200, phone: undefined, website: undefined, instagram: '@hotelbusiness', facebook: undefined, address: 'Rua 90, 800', city: 'Goiânia', state: 'GO', neighborhood: 'Setor Sul', openingHours: '24h', rating: 4.9, reviewCount: 350, source: 'mock' },
];

export class MockBusinessDataProvider implements BusinessDataProvider {
  name = 'MockBusinessDataProvider';

  async isAvailable(): Promise<boolean> {
    return true;
  }

  async search(params: SearchParams): Promise<RawBusinessData[]> {
    const { niche, city, state, neighborhood, radiusKm, limit, lat, lon } = params;

    const queryNiche = removeAccents(niche.toLowerCase());
    const queryCity = removeAccents(city.toLowerCase());
    const queryState = removeAccents(state.toLowerCase());
    const queryNeighborhood = neighborhood ? removeAccents(neighborhood.toLowerCase()) : undefined;

    const filtered = mockData.filter(business => {
      // Filter by niche (check both category and name)
      const busCategory = removeAccents(business.category.toLowerCase());
      const busName = removeAccents(business.name.toLowerCase());
      
      const matchesNiche = busCategory.includes(queryNiche) || busName.includes(queryNiche) || queryNiche.includes(busCategory);
      if (!matchesNiche) return false;

      // Filter by city and state
      const busCity = business.city ? removeAccents(business.city.toLowerCase()) : '';
      const busState = business.state ? removeAccents(business.state.toLowerCase()) : '';
      
      if (busCity !== queryCity) return false;
      if (busState !== queryState) return false;

      // Filter by neighborhood if provided
      if (queryNeighborhood && business.neighborhood) {
        const busNeighborhood = removeAccents(business.neighborhood.toLowerCase());
        if (busNeighborhood !== queryNeighborhood) return false;
      }

      // Filter by radius if lat/lon provided
      if (lat !== undefined && lon !== undefined && radiusKm > 0) {
        const distance = haversineDistance(lat, lon, business.lat, business.lon);
        if (distance > radiusKm) return false;
      }

      return true;
    });

    return filtered.slice(0, limit);
  }
}
